# Generated by Django 3.1.7 on 2021-03-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vinil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinil', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArtista', models.CharField(max_length=200)),
                ('tituloDisco', models.CharField(max_length=200)),
                ('pais', models.CharField(blank=True, max_length=200)),
                ('anoLancamento', models.CharField(blank=True, max_length=10)),
                ('seloGavadora', models.CharField(blank=True, max_length=200)),
                ('cor', models.CharField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discos.capa')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discos.tamanho')),
                ('vinil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='discos.vinil')),
            ],
        ),
    ]
