# Generated by Django 3.1.7 on 2021-03-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='seloGavadora',
            new_name='seloGravadora',
        ),
    ]
