# Generated by Django 3.1.7 on 2021-03-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0002_auto_20210324_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='nomeArtista',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='tituloDisco',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='seloGravadora',
            new_name='gravadora',
        ),
        migrations.RenameField(
            model_name='disco',
            old_name='anoLancamento',
            new_name='lancamento',
        ),
    ]
