# Generated by Django 3.1.7 on 2021-04-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0003_auto_20210325_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='capa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discos.capa'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='foto',
            field=models.ImageField(upload_to='pictures/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='tamanho',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discos.tamanho'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='vinil',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discos.vinil'),
        ),
    ]
