# Generated by Django 3.1.7 on 2021-04-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discos', '0005_disco_qtd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disco',
            name='qtd',
        ),
    ]
